apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pipeline-source
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/pandorabe/quarkus-sample.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pipeline-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-test/quarkus-app-tekton
